# define the following variables:
# connection
# subscriptionId
# environmentName
# location

name: Deploy Bicep files

trigger:
- v9

pool:
  vmImage: ubuntu-latest

steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: '$(connection)'
    subscriptionId: '$(subscriptionId)'
    action: 'Create Or Update Resource Group'
    resourceGroupName: '$(environmentName)'
    location: '$(location)'
    templateLocation: 'Linked artifact'
    csmFile: './infrastructure/azure/main.bicep'
    csmParametersFile: './infrastructure/azure/main.parameters.json'
 #   overrideParameters: '-name $(resourceGroup) -location $(location)'
    deploymentMode: 'Incremental'